# Generated by Django 2.2.7 on 2019-12-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
