# Generated by Django 2.2.7 on 2019-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='question_text',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pub_date',
            new_name='pub_time',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
