# Generated by Django 2.2.7 on 2019-12-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree', '0003_auto_20191201_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
