# Generated by Django 2.2.7 on 2019-12-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree', '0006_auto_20191207_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(default=42.4406),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.FloatField(default=-76.4966),
        ),
    ]
